"""
generate_supabase_config.py
Build-time generator: reads the Supabase URL/publishable key out of
frontend/.env.local and writes backend/_supabase_secrets.py, which gets
bundled into the packaged binary by PyInstaller.

Run from the build scripts before PyInstaller. The generated file is
gitignored so the key is never committed — it only ever reaches the shipped
app, where it already lives inside the frontend bundle anyway.
"""

import sys
from pathlib import Path

from supabase_config import frontend_env_local_path, read_from_frontend_env_local

OUTPUT_PATH = Path(__file__).resolve().parent / "_supabase_secrets.py"

TEMPLATE = '''"""
AUTO-GENERATED by generate_supabase_config.py at build time. Do not edit,
and do not commit — this file is gitignored.
Source: frontend/.env.local
"""

SUPABASE_URL = {url!r}
SUPABASE_ANON_KEY = {key!r}
'''


def main() -> int:
    url, key = read_from_frontend_env_local()

    if not url or not key:
        print("", flush=True)
        print("=" * 70, flush=True)
        print("  WARNING: Supabase credentials not found.", flush=True)
        print(f"  Looked in: {frontend_env_local_path()}", flush=True)
        print("  Expected keys: VITE_SUPABASE_URL, VITE_SUPABASE_ANON_KEY", flush=True)
        print("", flush=True)
        print("  The build will continue, but the packaged backend will NOT be", flush=True)
        print("  able to resolve a user's real plan: every account will be", flush=True)
        print("  treated as Free Trial, blocking paid resolutions and batch.", flush=True)
        print("=" * 70, flush=True)
        print("", flush=True)

    OUTPUT_PATH.write_text(TEMPLATE.format(url=url, key=key), encoding="utf-8")

    if url and key:
        # Never print the key itself.
        print(f"[OK] Wrote {OUTPUT_PATH.name} (url={url}, key=***{key[-4:]})", flush=True)
    else:
        print(f"[WARN] Wrote {OUTPUT_PATH.name} with empty credentials.", flush=True)

    return 0


if __name__ == "__main__":
    sys.exit(main())
