# -*- mode: python ; coding: utf-8 -*-
import os
import glob
from PyInstaller.utils.hooks import collect_all, collect_data_files
from PyInstaller.utils.hooks import copy_metadata

datas = []
binaries = []
hiddenimports = ['imageio', 'imageio_ffmpeg', 'moviepy', 'moviepy.editor', 'moviepy.video.io.ffmpeg_reader', 'moviepy.video.io.ffmpeg_writer', 'moviepy.audio.io.ffmpeg_audiowriter', 'moviepy.audio.io.AudioFileClip', 'moviepy.video.VideoClip', 'moviepy.audio.AudioClip', 'PIL', 'numpy', 'uvicorn.lifespan.off', 'uvicorn.lifespan.on', 'uvicorn.lifespan', 'uvicorn.protocols.websockets.auto', 'uvicorn.protocols.websockets.wsproto_impl', 'uvicorn.protocols.websockets_impl', 'uvicorn.protocols.http.auto', 'uvicorn.protocols.http.h11_impl', 'uvicorn.protocols.http.httptools_impl', 'uvicorn.protocols.websockets', 'uvicorn.protocols.http', 'uvicorn.protocols', 'uvicorn.loops.auto', 'uvicorn.loops.asyncio', 'uvicorn.loops.uvloop', 'uvicorn.loops', 'uvicorn.logging']
datas += copy_metadata('imageio')
datas += copy_metadata('imageio-ffmpeg')
datas += copy_metadata('moviepy')
datas += copy_metadata('decorator')
datas += copy_metadata('proglog')
tmp_ret = collect_all('imageio')
datas += tmp_ret[0]; binaries += tmp_ret[1]; hiddenimports += tmp_ret[2]
tmp_ret = collect_all('imageio_ffmpeg')
datas += tmp_ret[0]; binaries += tmp_ret[1]; hiddenimports += tmp_ret[2]

tmp_ret = collect_all('faster_whisper')
datas += tmp_ret[0]
binaries += tmp_ret[1]
hiddenimports += tmp_ret[2]
datas += collect_data_files('faster_whisper')

# Bundle the caption/text-overlay font files so ffmpeg's `fontsdir` filter
# can find them in a packaged build. Read at runtime via sys._MEIPASS in
# media_helpers.py / caption_engine.py — the source-tree lookup used in dev
# doesn't resolve once the app is frozen.
_fonts_src_dir = os.path.join(SPECPATH, '..', 'frontend', 'public', 'fonts')
datas += [(f, 'fonts') for f in glob.glob(os.path.join(_fonts_src_dir, '*'))]

# Supabase credentials generated by generate_supabase_config.py (run by the
# build scripts just before PyInstaller). Declared explicitly because it is
# imported inside a try/except in supabase_config.py — if it were missed,
# server-side plan checks would silently downgrade every user to Free Trial.
if os.path.exists(os.path.join(SPECPATH, '_supabase_secrets.py')):
    hiddenimports += ['_supabase_secrets']

# ── Text to Speech (Piper) ───────────────────────────────────────────────────
# piper ships espeak-ng phonemization data (~19 MB) inside its package. Without
# it PiperVoice.load() cannot phonemize and every synthesis fails in a frozen
# build, so the data files must be collected explicitly.
#
# Deliberately NOT collect_all('piper'): on piper-tts 1.5.0+ that walks
# piper.train.*, which imports torch — a dependency this integration
# intentionally avoids (it would add ~1.8 GB and pull in the XTTS stack we
# excluded). The pinned 1.4.2 has no piper.train, so collect_all would be
# safe there today, but scoping stays explicit so a future version bump
# can't silently drag torch into the build. All eight modules below are
# verified to exist in 1.4.2 and are exactly what the synthesis path
# imports (checked via sys.modules after `from piper import PiperVoice`).
datas += collect_data_files('piper')
hiddenimports += [
    'piper', 'piper.config', 'piper.const', 'piper.phoneme_ids',
    'piper.phonemize_espeak', 'piper.tashkeel', 'piper.voice',
    # Native espeak-ng bridge extension (espeakbridge.so/.pyd) — not picked up
    # by collect_dynamic_libs, so it's referenced as a submodule import.
    'piper.espeakbridge',
]

tmp_ret = collect_all('onnxruntime')
datas += tmp_ret[0]; binaries += tmp_ret[1]; hiddenimports += tmp_ret[2]

# Cloud TTS engine + Auto-Translate + offline language detection. All small
# pure-Python packages, but each is imported lazily inside functions so
# PyInstaller's static analysis can miss them. py3langid ships its own
# compressed language model as package data.
hiddenimports += [
    'edge_tts', 'aiohttp',
    'deep_translator', 'deep_translator.google',
    'py3langid',
]
datas += collect_data_files('py3langid')

# The voice catalog index is read at runtime via sys._MEIPASS (see
# tts_helpers._index_path) to populate the voice picker.
datas += [(os.path.join(SPECPATH, 'piper_voices_index.json'), '.')]

# Voice models bundled into the installer, if the build pre-downloaded any
# into backend/piper_voices/. Anything not bundled is fetched once on first
# use and cached under get_data_dir()/models/piper, so the full catalog stays
# selectable without shipping all ~9 GB of voices inside the installer.
_voices_src_dir = os.path.join(SPECPATH, 'piper_voices')
if os.path.isdir(_voices_src_dir):
    _voice_files = (
        glob.glob(os.path.join(_voices_src_dir, '*.onnx'))
        + glob.glob(os.path.join(_voices_src_dir, '*.onnx.json'))
    )
    datas += [(f, 'piper_voices') for f in _voice_files]


a = Analysis(
    ['desktop_backend_launcher.py'],
    pathex=[],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='syncframe-backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='syncframe-backend',
)
