/**
 * AUTO-GENERATED FILE - DO NOT EDIT BY HAND.
 *
 * Source:    shared/caption_presets.json
 * Generator: scripts/generate_caption_presets.py
 *
 * Edit the JSON and re-run the generator; hand edits here will be
 * overwritten and will silently desync the renderer from the preview.
 */

export interface GeneratedPresetMeta {
  name: string
  categories: string[]
}

export const CAPTION_SCHEMA_VERSION = 2

export const FALLBACK_DEFAULTS: Record<string, any> = {
  "fontFamily": "Roboto",
  "fontWeight": "bold",
  "fontScale": 1.0,
  "textTransform": "original",
  "letterSpacing": 0,
  "lineHeight": "normal",
  "textAlign": "center",
  "position": "bottom",
  "verticalOffset": 0,
  "maxWidth": 85,
  "maxLines": 2,
  "maxWords": 5,
  "safeMargin": 5,
  "primaryColor": "#FFFFFF",
  "accentColor": "#FF0000",
  "accentMode": "none",
  "outlineStyle": "medium",
  "outlineColor": "#000000",
  "shadowStyle": "none",
  "shadowColor": "#000000",
  "boxStyle": "none",
  "boxColor": "#000000",
  "karaokeMode": "none",
  "activeColor": "#FFE600",
  "inactiveAlpha": 0,
  "activeScale": 100,
  "activePop": 0,
  "activeOutlineColor": "",
  "activeBoxColor": "",
}

export const BUILT_IN_DEFINITIONS: Record<string, Record<string, any>> = {
  "viral_bold": {
    "karaokeMode": "none",
    "activeColor": "#FFE600",
    "inactiveAlpha": 0,
    "activeScale": 100,
    "activePop": 0,
    "activeOutlineColor": "",
    "activeBoxColor": "",
    "fontFamily": "Roboto",
    "fontWeight": "900",
    "fontScale": 1.0,
    "textTransform": "uppercase",
    "letterSpacing": 0.02,
    "lineHeight": "tight",
    "textAlign": "center",
    "position": "lower_center",
    "verticalOffset": 0,
    "maxWidth": 85,
    "maxLines": 2,
    "maxWords": 5,
    "primaryColor": "#FFFFFF",
    "accentColor": "#FFE600",
    "accentMode": "second_line",
    "outlineStyle": "thick",
    "outlineColor": "#000000",
    "shadowStyle": "medium",
    "shadowColor": "#FFE600",
    "boxStyle": "none",
  },
  "impact_stack": {
    "karaokeMode": "none",
    "activeColor": "#FFE600",
    "inactiveAlpha": 0,
    "activeScale": 100,
    "activePop": 0,
    "activeOutlineColor": "",
    "activeBoxColor": "",
    "fontFamily": "Anton",
    "fontWeight": "400",
    "fontScale": 1.0,
    "textTransform": "uppercase",
    "letterSpacing": 0.04,
    "lineHeight": "tight",
    "textAlign": "center",
    "position": "bottom",
    "maxWidth": 90,
    "maxLines": 3,
    "maxWords": 4,
    "primaryColor": "#FFFFFF",
    "accentColor": "#A855F7",
    "accentMode": "alternate_phrase",
    "outlineStyle": "medium",
    "outlineColor": "#A855F7",
    "shadowStyle": "strong",
    "shadowColor": "#000000",
    "boxStyle": "none",
  },
  "highlight_bar": {
    "karaokeMode": "none",
    "activeColor": "#FFE600",
    "inactiveAlpha": 0,
    "activeScale": 100,
    "activePop": 0,
    "activeOutlineColor": "",
    "activeBoxColor": "",
    "fontFamily": "Inter",
    "fontWeight": "900",
    "fontScale": 1.0,
    "textTransform": "uppercase",
    "lineHeight": "tight",
    "textAlign": "center",
    "position": "lower_center",
    "maxWidth": 80,
    "maxLines": 2,
    "maxWords": 6,
    "primaryColor": "#000000",
    "accentColor": "#FF8A00",
    "accentMode": "none",
    "outlineStyle": "none",
    "shadowStyle": "none",
    "boxStyle": "medium",
    "boxColor": "#FF8A00",
  },
  "neon_pop": {
    "karaokeMode": "none",
    "activeColor": "#FFE600",
    "inactiveAlpha": 0,
    "activeScale": 100,
    "activePop": 0,
    "activeOutlineColor": "",
    "activeBoxColor": "",
    "fontFamily": "Montserrat",
    "fontWeight": "800",
    "fontScale": 1.0,
    "textTransform": "uppercase",
    "letterSpacing": 0.03,
    "lineHeight": "tight",
    "textAlign": "center",
    "position": "bottom",
    "maxWidth": 85,
    "maxLines": 2,
    "maxWords": 4,
    "primaryColor": "#FFFFFF",
    "accentColor": "#00E5FF",
    "accentMode": "none",
    "outlineStyle": "thin",
    "outlineColor": "#000000",
    "shadowStyle": "strong",
    "shadowColor": "#00E5FF",
    "boxStyle": "none",
  },
  "minimal": {
    "karaokeMode": "none",
    "activeColor": "#FFE600",
    "inactiveAlpha": 0,
    "activeScale": 100,
    "activePop": 0,
    "activeOutlineColor": "",
    "activeBoxColor": "",
    "fontFamily": "Inter",
    "fontWeight": "400",
    "fontScale": 0.8,
    "textTransform": "original",
    "letterSpacing": 0.01,
    "lineHeight": "relaxed",
    "textAlign": "center",
    "position": "bottom",
    "maxWidth": 90,
    "maxLines": 2,
    "maxWords": 8,
    "primaryColor": "#FFFFFF",
    "accentColor": "#CCCCCC",
    "accentMode": "none",
    "outlineStyle": "none",
    "shadowStyle": "soft",
    "shadowColor": "#000000",
    "boxStyle": "none",
  },
  "hot_take": {
    "karaokeMode": "none",
    "activeColor": "#FFE600",
    "inactiveAlpha": 0,
    "activeScale": 100,
    "activePop": 0,
    "activeOutlineColor": "",
    "activeBoxColor": "",
    "fontFamily": "Bangers",
    "fontWeight": "400",
    "fontScale": 1.2,
    "textTransform": "uppercase",
    "letterSpacing": 0.02,
    "lineHeight": "tight",
    "textAlign": "center",
    "position": "center",
    "maxWidth": 95,
    "maxLines": 2,
    "maxWords": 3,
    "primaryColor": "#3333FF",
    "accentColor": "#FF6633",
    "accentMode": "none",
    "outlineStyle": "thick",
    "outlineColor": "#FF6633",
    "shadowStyle": "none",
    "boxStyle": "none",
  },
  "clean_subtitle": {
    "karaokeMode": "none",
    "activeColor": "#FFE600",
    "inactiveAlpha": 0,
    "activeScale": 100,
    "activePop": 0,
    "activeOutlineColor": "",
    "activeBoxColor": "",
    "fontFamily": "Roboto",
    "fontWeight": "400",
    "fontScale": 0.9,
    "textTransform": "original",
    "letterSpacing": 0,
    "lineHeight": "normal",
    "textAlign": "center",
    "position": "bottom",
    "maxWidth": 85,
    "maxLines": 2,
    "maxWords": 10,
    "primaryColor": "#EAEAEA",
    "accentColor": "#FFFFFF",
    "accentMode": "none",
    "outlineStyle": "thin",
    "outlineColor": "#000000",
    "shadowStyle": "soft",
    "shadowColor": "#000000",
    "boxStyle": "none",
  },
  "documentary": {
    "karaokeMode": "none",
    "activeColor": "#FFE600",
    "inactiveAlpha": 0,
    "activeScale": 100,
    "activePop": 0,
    "activeOutlineColor": "",
    "activeBoxColor": "",
    "fontFamily": "Lora",
    "fontWeight": "400",
    "fontScale": 0.85,
    "textTransform": "original",
    "letterSpacing": 0.01,
    "lineHeight": "relaxed",
    "textAlign": "left",
    "position": "bottom",
    "maxWidth": 90,
    "maxLines": 2,
    "maxWords": 12,
    "primaryColor": "#F5F5F5",
    "accentColor": "#FFCC00",
    "accentMode": "none",
    "outlineStyle": "none",
    "shadowStyle": "medium",
    "shadowColor": "#000000",
    "boxStyle": "none",
  },
  "podcast_bold": {
    "karaokeMode": "none",
    "activeColor": "#FFE600",
    "inactiveAlpha": 0,
    "activeScale": 100,
    "activePop": 0,
    "activeOutlineColor": "",
    "activeBoxColor": "",
    "fontFamily": "Anton",
    "fontWeight": "400",
    "fontScale": 1.1,
    "textTransform": "uppercase",
    "letterSpacing": 0,
    "lineHeight": "tight",
    "textAlign": "center",
    "position": "center",
    "maxWidth": 80,
    "maxLines": 3,
    "maxWords": 3,
    "primaryColor": "#FFFFFF",
    "accentColor": "#00FF66",
    "accentMode": "first_word",
    "outlineStyle": "medium",
    "outlineColor": "#000000",
    "shadowStyle": "none",
    "boxStyle": "none",
  },
  "soft_box": {
    "karaokeMode": "none",
    "activeColor": "#FFE600",
    "inactiveAlpha": 0,
    "activeScale": 100,
    "activePop": 0,
    "activeOutlineColor": "",
    "activeBoxColor": "",
    "fontFamily": "Lato",
    "fontWeight": "700",
    "fontScale": 0.9,
    "textTransform": "original",
    "letterSpacing": 0,
    "lineHeight": "normal",
    "textAlign": "center",
    "position": "lower_center",
    "maxWidth": 85,
    "maxLines": 2,
    "maxWords": 8,
    "primaryColor": "#FFFFFF",
    "accentColor": "#FF3399",
    "accentMode": "none",
    "outlineStyle": "none",
    "shadowStyle": "none",
    "boxStyle": "subtle",
    "boxColor": "#000000",
  },
  "punch_yellow": {
    "karaokeMode": "none",
    "activeColor": "#FFE600",
    "inactiveAlpha": 0,
    "activeScale": 100,
    "activePop": 0,
    "activeOutlineColor": "",
    "activeBoxColor": "",
    "fontFamily": "Inter",
    "fontWeight": "900",
    "fontScale": 1.1,
    "textTransform": "uppercase",
    "letterSpacing": 0.05,
    "lineHeight": "tight",
    "textAlign": "center",
    "position": "center",
    "maxWidth": 80,
    "maxLines": 2,
    "maxWords": 4,
    "primaryColor": "#FFE600",
    "accentColor": "#FFFFFF",
    "accentMode": "none",
    "outlineStyle": "thick",
    "outlineColor": "#000000",
    "shadowStyle": "strong",
    "shadowColor": "#000000",
    "boxStyle": "none",
  },
  "mono_tech": {
    "karaokeMode": "none",
    "activeColor": "#FFE600",
    "inactiveAlpha": 0,
    "activeScale": 100,
    "activePop": 0,
    "activeOutlineColor": "",
    "activeBoxColor": "",
    "fontFamily": "Roboto Condensed",
    "fontWeight": "700",
    "fontScale": 0.85,
    "textTransform": "uppercase",
    "letterSpacing": 0.1,
    "lineHeight": "normal",
    "textAlign": "left",
    "position": "bottom",
    "maxWidth": 90,
    "maxLines": 3,
    "maxWords": 6,
    "primaryColor": "#00FF00",
    "accentColor": "#FFFFFF",
    "accentMode": "none",
    "outlineStyle": "none",
    "shadowStyle": "soft",
    "shadowColor": "#00FF00",
    "boxStyle": "subtle",
    "boxColor": "#002200",
  },
  "cinema_clean": {
    "karaokeMode": "none",
    "activeColor": "#FFE600",
    "inactiveAlpha": 0,
    "activeScale": 100,
    "activePop": 0,
    "activeOutlineColor": "",
    "activeBoxColor": "",
    "fontFamily": "Playfair Display",
    "fontWeight": "400",
    "fontScale": 0.75,
    "textTransform": "original",
    "letterSpacing": 0.1,
    "lineHeight": "relaxed",
    "textAlign": "center",
    "position": "bottom",
    "maxWidth": 90,
    "maxLines": 2,
    "maxWords": 8,
    "primaryColor": "#FFFFFF",
    "accentColor": "#E0E0E0",
    "accentMode": "none",
    "outlineStyle": "none",
    "shadowStyle": "none",
    "boxStyle": "none",
  },
  "news_bar": {
    "karaokeMode": "none",
    "activeColor": "#FFE600",
    "inactiveAlpha": 0,
    "activeScale": 100,
    "activePop": 0,
    "activeOutlineColor": "",
    "activeBoxColor": "",
    "fontFamily": "Oswald",
    "fontWeight": "700",
    "fontScale": 0.9,
    "textTransform": "uppercase",
    "letterSpacing": 0,
    "lineHeight": "normal",
    "textAlign": "left",
    "position": "bottom",
    "maxWidth": 100,
    "maxLines": 1,
    "maxWords": 15,
    "primaryColor": "#FFFFFF",
    "accentColor": "#FF0000",
    "accentMode": "none",
    "outlineStyle": "none",
    "shadowStyle": "soft",
    "shadowColor": "#000000",
    "boxStyle": "medium",
    "boxColor": "#000000",
  },
  "electric_blue": {
    "karaokeMode": "none",
    "activeColor": "#FFE600",
    "inactiveAlpha": 0,
    "activeScale": 100,
    "activePop": 0,
    "activeOutlineColor": "",
    "activeBoxColor": "",
    "fontFamily": "Inter",
    "fontWeight": "900",
    "fontScale": 1.0,
    "textTransform": "uppercase",
    "letterSpacing": 0.03,
    "lineHeight": "tight",
    "textAlign": "center",
    "position": "center",
    "maxWidth": 80,
    "maxLines": 3,
    "maxWords": 5,
    "primaryColor": "#00FFFF",
    "accentColor": "#FFFFFF",
    "accentMode": "alternate_phrase",
    "outlineStyle": "medium",
    "outlineColor": "#0000FF",
    "shadowStyle": "glow",
    "shadowColor": "#00FFFF",
    "boxStyle": "none",
  },
  "red_alert": {
    "karaokeMode": "none",
    "activeColor": "#FFE600",
    "inactiveAlpha": 0,
    "activeScale": 100,
    "activePop": 0,
    "activeOutlineColor": "",
    "activeBoxColor": "",
    "fontFamily": "Anton",
    "fontWeight": "400",
    "fontScale": 1.25,
    "textTransform": "uppercase",
    "letterSpacing": 0.05,
    "lineHeight": "tight",
    "textAlign": "center",
    "position": "center",
    "maxWidth": 90,
    "maxLines": 2,
    "maxWords": 3,
    "primaryColor": "#FF0000",
    "accentColor": "#FFFFFF",
    "accentMode": "first_word",
    "outlineStyle": "thick",
    "outlineColor": "#000000",
    "shadowStyle": "strong",
    "shadowColor": "#FF0000",
    "boxStyle": "none",
  },
  "karaoke_pop": {
    "karaokeMode": "word_window",
    "activeColor": "#FFE600",
    "inactiveAlpha": 0,
    "activeScale": 112,
    "activePop": 80,
    "activeOutlineColor": "",
    "activeBoxColor": "",
    "fontFamily": "Inter",
    "fontWeight": "900",
    "fontScale": 1.0,
    "textTransform": "uppercase",
    "letterSpacing": 0.02,
    "lineHeight": "tight",
    "textAlign": "center",
    "position": "lower_center",
    "maxWidth": 85,
    "maxLines": 2,
    "maxWords": 4,
    "primaryColor": "#FFFFFF",
    "accentColor": "#FFE600",
    "accentMode": "none",
    "outlineStyle": "thick",
    "outlineColor": "#000000",
    "shadowStyle": "medium",
    "shadowColor": "#000000",
    "boxStyle": "none",
  },
  "tiktok_bounce": {
    "karaokeMode": "word_window",
    "activeColor": "#000000",
    "inactiveAlpha": 0,
    "activeScale": 108,
    "activePop": 90,
    "activeOutlineColor": "",
    "activeBoxColor": "#00E5A0",
    "fontFamily": "Anton",
    "fontWeight": "400",
    "fontScale": 1.05,
    "textTransform": "uppercase",
    "letterSpacing": 0.03,
    "lineHeight": "tight",
    "textAlign": "center",
    "position": "center",
    "maxWidth": 85,
    "maxLines": 2,
    "maxWords": 3,
    "primaryColor": "#FFFFFF",
    "accentColor": "#000000",
    "accentMode": "none",
    "outlineStyle": "medium",
    "outlineColor": "#000000",
    "shadowStyle": "none",
    "shadowColor": "#000000",
    "boxStyle": "none",
  },
  "word_glow": {
    "karaokeMode": "word_window",
    "activeColor": "#00E5FF",
    "inactiveAlpha": 100,
    "activeScale": 104,
    "activePop": 70,
    "activeOutlineColor": "#00E5FF",
    "activeBoxColor": "",
    "fontFamily": "Montserrat",
    "fontWeight": "800",
    "fontScale": 1.0,
    "textTransform": "uppercase",
    "letterSpacing": 0.03,
    "lineHeight": "tight",
    "textAlign": "center",
    "position": "lower_center",
    "maxWidth": 85,
    "maxLines": 2,
    "maxWords": 4,
    "primaryColor": "#FFFFFF",
    "accentColor": "#00E5FF",
    "accentMode": "none",
    "outlineStyle": "thin",
    "outlineColor": "#001018",
    "shadowStyle": "strong",
    "shadowColor": "#00E5FF",
    "boxStyle": "none",
  },
  "beast_mode": {
    "karaokeMode": "word_window",
    "activeColor": "#FF2222",
    "inactiveAlpha": 0,
    "activeScale": 118,
    "activePop": 60,
    "activeOutlineColor": "",
    "activeBoxColor": "",
    "fontFamily": "Anton",
    "fontWeight": "400",
    "fontScale": 1.3,
    "textTransform": "uppercase",
    "letterSpacing": 0.04,
    "lineHeight": "tight",
    "textAlign": "center",
    "position": "center",
    "maxWidth": 92,
    "maxLines": 2,
    "maxWords": 2,
    "primaryColor": "#FFFFFF",
    "accentColor": "#FF2222",
    "accentMode": "none",
    "outlineStyle": "thick",
    "outlineColor": "#000000",
    "shadowStyle": "strong",
    "shadowColor": "#000000",
    "boxStyle": "none",
  },
  "clean_karaoke": {
    "karaokeMode": "word_window",
    "activeColor": "#FFFFFF",
    "inactiveAlpha": 140,
    "activeScale": 100,
    "activePop": 0,
    "activeOutlineColor": "",
    "activeBoxColor": "",
    "fontFamily": "Inter",
    "fontWeight": "700",
    "fontScale": 0.9,
    "textTransform": "original",
    "letterSpacing": 0.01,
    "lineHeight": "normal",
    "textAlign": "center",
    "position": "bottom",
    "maxWidth": 88,
    "maxLines": 2,
    "maxWords": 6,
    "primaryColor": "#FFFFFF",
    "accentColor": "#FFFFFF",
    "accentMode": "none",
    "outlineStyle": "thin",
    "outlineColor": "#000000",
    "shadowStyle": "soft",
    "shadowColor": "#000000",
    "boxStyle": "none",
  },
  "neon_sweep": {
    "karaokeMode": "fill",
    "activeColor": "#00E5FF",
    "inactiveAlpha": 0,
    "activeScale": 100,
    "activePop": 0,
    "activeOutlineColor": "",
    "activeBoxColor": "",
    "fontFamily": "Montserrat",
    "fontWeight": "800",
    "fontScale": 1.0,
    "textTransform": "uppercase",
    "letterSpacing": 0.04,
    "lineHeight": "tight",
    "textAlign": "center",
    "position": "lower_center",
    "maxWidth": 85,
    "maxLines": 2,
    "maxWords": 5,
    "primaryColor": "#FF2FD0",
    "accentColor": "#00E5FF",
    "accentMode": "none",
    "outlineStyle": "medium",
    "outlineColor": "#12002A",
    "shadowStyle": "strong",
    "shadowColor": "#FF2FD0",
    "boxStyle": "none",
  },
  "typewriter": {
    "karaokeMode": "word_window",
    "activeColor": "#FFFFFF",
    "inactiveAlpha": 255,
    "activeScale": 100,
    "activePop": 0,
    "activeOutlineColor": "",
    "activeBoxColor": "",
    "fontFamily": "Roboto Condensed",
    "fontWeight": "700",
    "fontScale": 0.95,
    "textTransform": "original",
    "letterSpacing": 0.02,
    "lineHeight": "normal",
    "textAlign": "center",
    "position": "bottom",
    "maxWidth": 88,
    "maxLines": 2,
    "maxWords": 6,
    "primaryColor": "#FFFFFF",
    "accentColor": "#FFFFFF",
    "accentMode": "none",
    "outlineStyle": "thin",
    "outlineColor": "#000000",
    "shadowStyle": "soft",
    "shadowColor": "#000000",
    "boxStyle": "none",
  },
  "podcast_highlighter": {
    "karaokeMode": "word_window",
    "activeColor": "#111111",
    "inactiveAlpha": 0,
    "activeScale": 100,
    "activePop": 0,
    "activeOutlineColor": "",
    "activeBoxColor": "#FFE600",
    "fontFamily": "Inter",
    "fontWeight": "900",
    "fontScale": 0.95,
    "textTransform": "original",
    "letterSpacing": 0.01,
    "lineHeight": "normal",
    "textAlign": "center",
    "position": "lower_center",
    "maxWidth": 82,
    "maxLines": 2,
    "maxWords": 6,
    "primaryColor": "#FFFFFF",
    "accentColor": "#111111",
    "accentMode": "none",
    "outlineStyle": "thin",
    "outlineColor": "#000000",
    "shadowStyle": "none",
    "shadowColor": "#000000",
    "boxStyle": "none",
  },
  "cinematic_serif": {
    "karaokeMode": "none",
    "activeColor": "#FFE600",
    "inactiveAlpha": 0,
    "activeScale": 100,
    "activePop": 0,
    "activeOutlineColor": "",
    "activeBoxColor": "",
    "fontFamily": "Playfair Display",
    "fontWeight": "400",
    "fontScale": 0.8,
    "textTransform": "original",
    "letterSpacing": 0.08,
    "lineHeight": "relaxed",
    "textAlign": "center",
    "position": "bottom",
    "maxWidth": 88,
    "maxLines": 2,
    "maxWords": 9,
    "primaryColor": "#F7F3EA",
    "accentColor": "#D8C8A0",
    "accentMode": "none",
    "outlineStyle": "none",
    "outlineColor": "#000000",
    "shadowStyle": "soft",
    "shadowColor": "#000000",
    "boxStyle": "none",
  },
  "bold_stack": {
    "karaokeMode": "word_window",
    "activeColor": "#A855F7",
    "inactiveAlpha": 90,
    "activeScale": 106,
    "activePop": 75,
    "activeOutlineColor": "",
    "activeBoxColor": "",
    "fontFamily": "Anton",
    "fontWeight": "400",
    "fontScale": 1.0,
    "textTransform": "uppercase",
    "letterSpacing": 0.02,
    "lineHeight": "tight",
    "textAlign": "center",
    "position": "center",
    "maxWidth": 85,
    "maxLines": 3,
    "maxWords": 6,
    "primaryColor": "#FFFFFF",
    "accentColor": "#A855F7",
    "accentMode": "none",
    "outlineStyle": "medium",
    "outlineColor": "#1A0033",
    "shadowStyle": "medium",
    "shadowColor": "#000000",
    "boxStyle": "none",
  },
  "minimal_mono": {
    "karaokeMode": "word_window",
    "activeColor": "#000000",
    "inactiveAlpha": 0,
    "activeScale": 100,
    "activePop": 0,
    "activeOutlineColor": "",
    "activeBoxColor": "#FFFFFF",
    "fontFamily": "Roboto Condensed",
    "fontWeight": "700",
    "fontScale": 0.85,
    "textTransform": "uppercase",
    "letterSpacing": 0.12,
    "lineHeight": "normal",
    "textAlign": "center",
    "position": "bottom",
    "maxWidth": 90,
    "maxLines": 2,
    "maxWords": 7,
    "primaryColor": "#FFFFFF",
    "accentColor": "#000000",
    "accentMode": "none",
    "outlineStyle": "none",
    "outlineColor": "#000000",
    "shadowStyle": "none",
    "shadowColor": "#000000",
    "boxStyle": "none",
  },
  "gradient_punch": {
    "karaokeMode": "word_window",
    "activeColor": "#FF6B00",
    "inactiveAlpha": 0,
    "activeScale": 110,
    "activePop": 85,
    "activeOutlineColor": "",
    "activeBoxColor": "",
    "fontFamily": "Inter",
    "fontWeight": "900",
    "fontScale": 1.05,
    "textTransform": "uppercase",
    "letterSpacing": 0.03,
    "lineHeight": "tight",
    "textAlign": "center",
    "position": "lower_center",
    "maxWidth": 85,
    "maxLines": 2,
    "maxWords": 4,
    "primaryColor": "#FFFFFF",
    "accentColor": "#FF6B00",
    "accentMode": "none",
    "outlineStyle": "thick",
    "outlineColor": "#000000",
    "shadowStyle": "medium",
    "shadowColor": "#000000",
    "boxStyle": "none",
    "gradientCycle": ["#FF6B00", "#FF2FD0", "#00E5FF"],
  },
}

export const PRESET_META: Record<string, GeneratedPresetMeta> = {
  "viral_bold": {
    "name": "Viral Bold",
    "categories": ["Trending", "Bold", "Social"],
  },
  "impact_stack": {
    "name": "Impact Stack",
    "categories": ["Trending", "Bold"],
  },
  "highlight_bar": {
    "name": "Highlight Bar",
    "categories": ["Social", "Bold"],
  },
  "neon_pop": {
    "name": "Neon Pop",
    "categories": ["Trending", "Social"],
  },
  "minimal": {
    "name": "Minimal",
    "categories": ["Minimal", "Clean", "Classic"],
  },
  "hot_take": {
    "name": "Hot Take",
    "categories": ["Social", "Trending"],
  },
  "clean_subtitle": {
    "name": "Clean Sub",
    "categories": ["Clean", "Classic"],
  },
  "documentary": {
    "name": "Documentary",
    "categories": ["Cinematic", "Classic"],
  },
  "podcast_bold": {
    "name": "Podcast",
    "categories": ["Podcast", "Bold"],
  },
  "soft_box": {
    "name": "Soft Box",
    "categories": ["Minimal", "Clean"],
  },
  "punch_yellow": {
    "name": "Punch Yellow",
    "categories": ["Bold", "Social"],
  },
  "mono_tech": {
    "name": "Mono Tech",
    "categories": ["Minimal"],
  },
  "cinema_clean": {
    "name": "Cinema Clean",
    "categories": ["Cinematic", "Clean"],
  },
  "news_bar": {
    "name": "News Bar",
    "categories": ["Classic", "Bold"],
  },
  "electric_blue": {
    "name": "Electric Blue",
    "categories": ["Social", "Trending"],
  },
  "red_alert": {
    "name": "Red Alert",
    "categories": ["Trending", "Bold"],
  },
  "karaoke_pop": {
    "name": "Karaoke Pop",
    "categories": ["Karaoke", "Trending", "Bold"],
  },
  "tiktok_bounce": {
    "name": "TikTok Bounce",
    "categories": ["Karaoke", "Trending", "Social"],
  },
  "word_glow": {
    "name": "Word Glow",
    "categories": ["Karaoke", "Social"],
  },
  "beast_mode": {
    "name": "Beast Mode",
    "categories": ["Karaoke", "Bold", "Trending"],
  },
  "clean_karaoke": {
    "name": "Clean Karaoke",
    "categories": ["Karaoke", "Clean", "Minimal"],
  },
  "neon_sweep": {
    "name": "Neon Sweep",
    "categories": ["Karaoke", "Trending", "Social"],
  },
  "typewriter": {
    "name": "Typewriter",
    "categories": ["Karaoke", "Minimal", "Clean"],
  },
  "podcast_highlighter": {
    "name": "Podcast Highlighter",
    "categories": ["Karaoke", "Podcast", "Bold"],
  },
  "cinematic_serif": {
    "name": "Cinematic Serif",
    "categories": ["Cinematic", "Clean", "Classic"],
  },
  "bold_stack": {
    "name": "Bold Stack",
    "categories": ["Karaoke", "Bold", "Social"],
  },
  "minimal_mono": {
    "name": "Minimal Mono",
    "categories": ["Karaoke", "Minimal", "Clean"],
  },
  "gradient_punch": {
    "name": "Gradient Punch",
    "categories": ["Karaoke", "Trending", "Bold"],
  },
}

export const PRESET_ORDER: string[] = ["viral_bold", "impact_stack", "highlight_bar", "neon_pop", "minimal", "hot_take", "clean_subtitle", "documentary", "podcast_bold", "soft_box", "punch_yellow", "mono_tech", "cinema_clean", "news_bar", "electric_blue", "red_alert", "karaoke_pop", "tiktok_bounce", "word_glow", "beast_mode", "clean_karaoke", "neon_sweep", "typewriter", "podcast_highlighter", "cinematic_serif", "bold_stack", "minimal_mono", "gradient_punch"]

export const PRESET_CATEGORIES: string[] = ["Bold", "Cinematic", "Classic", "Clean", "Karaoke", "Minimal", "Podcast", "Social", "Trending"]

export const KARAOKE_PRESET_IDS: string[] = ["karaoke_pop", "tiktok_bounce", "word_glow", "beast_mode", "clean_karaoke", "neon_sweep", "typewriter", "podcast_highlighter", "bold_stack", "minimal_mono", "gradient_punch"]
